### ISSUE TITLE
Additonal property required - canonicalUnit

### ISSUE THREAD

**Issue by adamml** [adamml/opm-owl#1]
Add a property from a complex property to a canonical unit for Climate and Forecast Common Concepts work. Probably wants to be a sub property of unit of measure

**Comment by adamml** [comment]
Discussing with @neothemachine: this needs to be a [0..1] property, categorical observations do not have a unit of measure / canonincal unit and forcing them to have "dimensionless" is a fudge.

**Comment by letmaik** [comment]
Switching over from https://github.com/Reading-eScience-Centre/coveragejson/issues/39#issuecomment-158014465:

I have a feeling that CPM is more than CF, so why would canonicalUnit live within CF?

Again from [sweet](http://sweet.jpl.nasa.gov/2.3/propTemperature.owl):

``` xml
  <owl:Class rdf:about="#Temperature">
    <rdfs:subClassOf rdf:resource="&quan;#ThermodynamicQuantity"/>
    <rdfs:subClassOf>
      <owl:Restriction>
        <owl:hasValue rdf:resource="&units;#kelvin"/>
        <owl:onProperty rdf:resource="&screla;#hasDefaultUnit"/>
      </owl:Restriction>
    </rdfs:subClassOf>
    <rdfs:subClassOf>
      <owl:Restriction>
        <owl:onProperty rdf:resource="&screla;#measureOf" />
        <owl:allValuesFrom rdf:resource="&ener;#Heat"/>
      </owl:Restriction>
    </rdfs:subClassOf>
  </owl:Class>
```

So there's `http://sweet.jpl.nasa.gov/2.3/relaSci.owl#hasDefaultUnit`. Is that your canonical unit?

(By the way: Can you rename this issue to include canonical units in the title?)

**Comment by adamml** [comment]
You're right that CPM != CF, but until now, the only use case I have had for canonicalUnit comes from CF which is why I am unsure as to which namespace the property should live in.

Having said that, there is no CF namespace as yet so I will look at this in the next week or two.

**Comment by adamml** [comment]
Resolved in commit https://github.com/adamml/opm-owl/commit/31bb88868ed3f4b928948525afee81571e7ccf53
